BEGIN;
DO $$
DECLARE c1 text; c2 text; d1 text; d2 text; renewal text; value numeric; state text; succeeded boolean;
BEGIN
 INSERT INTO destekol."Campaign"(slug,title,summary,description,"goalAmount") VALUES('policy-test-'||gen_random_uuid(),'Policy test','Test','Test',1000) RETURNING id INTO c1;
 INSERT INTO destekol."Campaign"(slug,title,summary,description,"goalAmount") VALUES('policy-test-'||gen_random_uuid(),'Policy test','Test','Test',1000) RETURNING id INTO c2;
 INSERT INTO destekol."Donation"("campaignId","donorName","donorEmail",amount,currency,frequency,provider,"providerRef") VALUES(c1,'Policy test','policy-test@example.invalid',100,'usd','MONTHLY','STRIPE','cs_policy_test_1') RETURNING id INTO d1;
 INSERT INTO destekol."Donation"("campaignId","donorName","donorEmail",amount,currency,frequency,provider,"providerRef") VALUES(c2,'Policy test','policy-test@example.invalid',50,'usd','MONTHLY','STRIPE','cs_policy_test_2') RETURNING id INTO d2;
 succeeded := destekol.confirm_donation_payment(d1,'STRIPE','cs_policy_test_1',100,'USD','sub_policy_test_1','payment_policy_test_1');
 IF NOT succeeded THEN RAISE EXCEPTION 'First payment not confirmed'; END IF;
 succeeded := destekol.confirm_donation_payment(d1,'STRIPE','cs_policy_test_1',100,'USD','sub_policy_test_1','payment_policy_test_1');
 IF succeeded THEN RAISE EXCEPTION 'Duplicate payment confirmed twice'; END IF;
 SELECT "raisedAmount" INTO value FROM destekol."Campaign" WHERE id=c1;
 IF value<>100 THEN RAISE EXCEPTION 'Duplicate payment changed campaign'; END IF;
 BEGIN
   PERFORM destekol.confirm_donation_payment(d2,'STRIPE','cs_policy_test_2',1,'USD',NULL,'payment_policy_test_2');
   RAISE EXCEPTION 'Expected mismatch rejection';
 EXCEPTION WHEN OTHERS THEN IF SQLERRM='Expected mismatch rejection' THEN RAISE; END IF; END;
 PERFORM destekol.confirm_donation_payment(d2,'STRIPE','cs_policy_test_2',50,'USD','sub_policy_test_2','payment_policy_test_2');
 UPDATE destekol."Donation" SET "subscriptionStatus"='CANCELLED' WHERE id=d2;
 SELECT status::text INTO state FROM destekol."Donation" WHERE id=d2;
 IF state<>'COMPLETED' THEN RAISE EXCEPTION 'Cancellation changed payment status'; END IF;
 PERFORM destekol.record_donation_refund(d1,'STRIPE','refund_policy_1',20,'USD','Duplicate charge','PENDING');
 SELECT "refundedAmount" INTO value FROM destekol."Donation" WHERE id=d1;
 IF value<>0 THEN RAISE EXCEPTION 'Pending refund deducted money'; END IF;
 PERFORM destekol.record_donation_refund(d1,'STRIPE','refund_policy_1',20,'USD','Duplicate charge','SUCCEEDED');
 PERFORM destekol.record_donation_refund(d1,'STRIPE','refund_policy_1',20,'USD','Duplicate charge','SUCCEEDED');
 SELECT "raisedAmount" INTO value FROM destekol."Campaign" WHERE id=c1;
 IF value<>80 THEN RAISE EXCEPTION 'Partial or repeated refund incorrect'; END IF;
 SELECT "refundStatus" INTO state FROM destekol."Donation" WHERE id=d1;
 IF state<>'PARTIAL' THEN RAISE EXCEPTION 'Partial refund state incorrect'; END IF;
 PERFORM destekol.record_donation_refund(d1,'STRIPE','refund_policy_2',80,'USD','Requested refund','SUCCEEDED');
 SELECT "refundStatus" INTO state FROM destekol."Donation" WHERE id=d1;
 IF state<>'FULL' THEN RAISE EXCEPTION 'Full refund state incorrect'; END IF;
 SELECT "raisedAmount" INTO value FROM destekol."Campaign" WHERE id=c1;
 IF value<>0 THEN RAISE EXCEPTION 'Full refund balance incorrect'; END IF;
 SELECT "raisedAmount" INTO value FROM destekol."Campaign" WHERE id=c2;
 IF value<>50 THEN RAISE EXCEPTION 'Refund altered another campaign'; END IF;
 renewal := destekol.record_recurring_payment('sub_policy_test_2','STRIPE','payment_policy_test_2',50,'USD','TEST');
 IF renewal IS NOT NULL THEN RAISE EXCEPTION 'First subscription payment counted as renewal'; END IF;
 renewal := destekol.record_recurring_payment('sub_policy_test_2','STRIPE','invoice_policy_test_2',50,'USD','TEST');
 IF renewal IS NULL THEN RAISE EXCEPTION 'Renewal not recorded'; END IF;
 renewal := destekol.record_recurring_payment('sub_policy_test_2','STRIPE','invoice_policy_test_2',50,'USD','TEST');
 IF renewal IS NOT NULL THEN RAISE EXCEPTION 'Duplicate renewal recorded'; END IF;
 SELECT "raisedAmount" INTO value FROM destekol."Campaign" WHERE id=c2;
 IF value<>100 THEN RAISE EXCEPTION 'Renewal allocation incorrect'; END IF;
END $$;
ROLLBACK;
SELECT 'payment ledger checks passed; all test records rolled back' AS result;
