BEGIN;
DO $$ DECLARE c1 text; c2 text; o record; d text; test_order record; total numeric; raised numeric; n integer; blocked boolean;
BEGIN
 INSERT INTO destekol."Campaign"(slug,title,summary,description,"goalAmount") VALUES('paytr-fixture-'||gen_random_uuid()::text,'Fixture 1','Fixture','Fixture',100) RETURNING id INTO c1;
 INSERT INTO destekol."Campaign"(slug,title,summary,description,"goalAmount") VALUES('paytr-fixture-'||gen_random_uuid()::text,'Fixture 2','Fixture','Fixture',100) RETURNING id INTO c2;
 SELECT * INTO o FROM destekol.create_paytr_order(gen_random_uuid()::text,'fixture','DO'||replace(gen_random_uuid()::text,'-',''),'Fixture','fixture@destekol.test','USD',jsonb_build_array(jsonb_build_object('campaignId',c1,'amount',10,'frequency','ONE_TIME'),jsonb_build_object('campaignId',c2,'amount',20,'frequency','ONE_TIME')),'CARD',false,null,false);
 d:=o."donationId";
 blocked:=false;BEGIN PERFORM destekol.process_paytr_callback(o.oid,'success',29,'USD',false);EXCEPTION WHEN OTHERS THEN blocked:=true;END;
 IF NOT blocked THEN RAISE EXCEPTION 'Wrong amount accepted';END IF;
 IF NOT destekol.process_paytr_callback(o.oid,'success',30,'USD',false) THEN RAISE EXCEPTION 'Confirmation failed'; END IF;
 IF destekol.process_paytr_callback(o.oid,'success',30,'USD',false) THEN RAISE EXCEPTION 'Duplicate confirmed'; END IF;
 SELECT sum("raisedAmount"),sum("donorCount") INTO raised,n FROM destekol."Campaign" WHERE id IN (c1,c2);
 IF raised<>30 OR n<>2 THEN RAISE EXCEPTION 'Allocation double count'; END IF;
 PERFORM destekol.reserve_paytr_refund(d,'RF'||replace(gen_random_uuid()::text,'-',''),2,'Fixture');
 blocked:=false;BEGIN PERFORM destekol.reserve_paytr_refund(d,'blocked',2,'Fixture');EXCEPTION WHEN OTHERS THEN blocked:=true;END;
 IF NOT blocked THEN RAISE EXCEPTION 'Pending refund did not block another';END IF;
 PERFORM destekol.finish_paytr_refund(d,(SELECT "providerRefundId" FROM destekol."DonationRefund" WHERE "donationId"=d),'FAILED');
 PERFORM destekol.reserve_paytr_refund(d,'PARTIAL',5,'Fixture partial');
 PERFORM destekol.finish_paytr_refund(d,'PARTIAL','SUCCEEDED');
 PERFORM destekol.finish_paytr_refund(d,'PARTIAL','SUCCEEDED');
 SELECT sum("raisedAmount") INTO raised FROM destekol."Campaign" WHERE id IN (c1,c2);
 IF raised<>25 THEN RAISE EXCEPTION 'Partial refund allocation incorrect'; END IF;
 PERFORM destekol.reserve_paytr_refund(d,'FULL',25,'Fixture full');
 PERFORM destekol.finish_paytr_refund(d,'FULL','SUCCEEDED');
 IF NOT EXISTS(SELECT 1 FROM destekol."Donation" WHERE id=d AND status::text='REFUNDED' AND "refundedAmount"=30 AND "refundStatus"='FULL') THEN RAISE EXCEPTION 'Full refund incorrect';END IF;
 SELECT sum("raisedAmount") INTO raised FROM destekol."Campaign" WHERE id IN (c1,c2);
 IF raised<>0 THEN RAISE EXCEPTION 'Full refund allocation incorrect'; END IF;
 SELECT * INTO test_order FROM destekol.create_paytr_order(gen_random_uuid()::text,'fixturetest','DO'||replace(gen_random_uuid()::text,'-',''),'Fixture','fixture@destekol.test','USD',jsonb_build_array(jsonb_build_object('campaignId',c1,'amount',100,'frequency','ONE_TIME')),'CARD',true,null,false);
 PERFORM destekol.process_paytr_callback(test_order.oid,'success',100,'USD',true);
 IF EXISTS(SELECT 1 FROM destekol."Donation" WHERE id=test_order."donationId" AND status::text='COMPLETED') THEN RAISE EXCEPTION 'Test recorded as real funds';END IF;
 SELECT "raisedAmount" INTO raised FROM destekol."Campaign" WHERE id=c1;
 IF raised<>0 THEN RAISE EXCEPTION 'Test changed campaign funds';END IF;
 IF has_function_privilege('anon','destekol.process_paytr_callback(text,text,numeric,text,boolean)','execute') THEN RAISE EXCEPTION 'Public can confirm payments';END IF;
END $$;
ROLLBACK;
