const fs=require('fs'),ts=require('typescript'),assert=require('node:assert/strict'),test=require('node:test'),{createHmac}=require('crypto');const {NextRequest}=require('next/server');
function load(p,mocks={}){const m={exports:{}};const js=ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;new Function('require','module','exports',js)(x=>x in mocks?mocks[x]:require(x),m,m.exports);return m.exports;}
const protocol=load('lib/paytr-protocol.ts'),lifecycle=load('lib/payment-lifecycle.ts');
const creds={merchantId:'123',merchantKey:'fixture-key',merchantSalt:'fixture-salt',testMode:false};
const settings={mode:'LIVE',cardEnabled:true,bankEnabled:true,currencies:['USD','TRY']};
const config={enabled:true,testMode:false,card:true,bank:true,monthly:false,currencies:['USD','TRY']};
const req=body=>new NextRequest('http://localhost/api/payments/paytr/checkout',{method:'POST',body:JSON.stringify(body)});
const body={name:'Fixture',email:'fixture@destekol.test',phone:'+905551234567',address:'Fixture address',method:'CARD',currency:'USD',requestKey:'12345678-1234-1234-1234-123456789012',locale:'en',items:[{campaignId:'c1',amount:10,frequency:'ONE_TIME'},{campaignId:'c2',amount:20,frequency:'ONE_TIME'}],policiesAccepted:true};
function checkoutFixture({disabled=false,saveError=false,existing=false,tokenState='READY',gatewayError=null}={}){let saved,tokenCalls=0,grant=0,updates=[];const db={from:table=>({select(){return this},eq(){return this},in:async()=>({data:[{id:'c1',title:'One',currency:'USD',isActive:true},{id:'c2',title:'Two',currency:'USD',isActive:true}]}),single:async()=>({data:{testMode:false}}),update(v){updates.push(v);return this},then(resolve){return Promise.resolve(resolve({error:null}))}}),rpc:async(name,args)=>{saved=args;return{error:saveError?{}:null,data:[{donationId:'fixture',oid:'DOFixture',tokenState,iframeTokenEncrypted:existing?'encrypted':null,created:!existing}]}}};
const route=load('app/api/payments/paytr/checkout/route.ts',{'@/lib/request-limit':{enforceRequestLimit:async()=>null,clientIdentity:()=> '203.0.113.1'},'@/lib/payment-lifecycle':lifecycle,'@/lib/supabase':{getSupabase:()=>db},'@/lib/request-site':{getRequestSite:()=>({url:'https://destekol.org'})},'@/lib/paytr-settings':{getPayTRSettings:async()=>settings,publicPaymentConfig:()=>({...config,enabled:!disabled}),payTRCredentials:()=>creds,encryptPaymentSecret:()=> 'encrypted',decryptPaymentSecret:()=> 'a'.repeat(32)},'@/lib/paytr-adapter':{GatewayRejected:class GatewayRejected extends Error{},requestPaymentToken:async(method,order,c,donor,url,locale,basket)=>{tokenCalls++;assert(saved);assert.equal(order.amount,30);assert.equal(order.currency,'USD');assert.deepEqual(basket,[['One','10.00',1],['Two','20.00',1]]);if(gatewayError)throw gatewayError;return 'a'.repeat(32)}},'@/lib/donation-return-access':{DONATION_ACCESS_COOKIE:'cookie',paymentLocale:v=>v||'tr',grantDonationAccess:async(r,id)=>{assert.equal(id,'fixture');grant++;return r;}}});return{route,saved:()=>saved,calls:()=>tokenCalls,grants:()=>grant,updates};}
test('checkout persists separate allocations before gateway token and grants guest access',async()=>{const f=checkoutFixture();const response=await f.route.POST(req(body));assert.equal(response.status,200);const data=await response.json();assert.equal(data.iframeUrl,'https://www.paytr.com/odeme/guvenli/'+'a'.repeat(32));assert.equal(f.saved().p_items.length,2);assert.equal(f.saved().p_currency,'USD');assert.equal(f.grants(),1);});
test('disabled payments, missing terms and monthly requests never contact gateway',async()=>{for(const [b,options,status]of [[body,{disabled:true},503],[{...body,policiesAccepted:false},{},400],[{...body,items:[{campaignId:null,amount:10,frequency:'MONTHLY'}]},{},400]]){const f=checkoutFixture(options),response=await f.route.POST(req(b));assert.equal(response.status,status);assert.equal(f.calls(),0);assert.equal(f.saved(),undefined);}});
test('save failure stops checkout and repeats reuse the persisted token',async()=>{let f=checkoutFixture({saveError:true});assert.equal((await f.route.POST(req(body))).status,503);assert.equal(f.calls(),0);f=checkoutFixture({existing:true});assert.equal((await f.route.POST(req(body))).status,200);assert.equal(f.calls(),0);});
test('unknown gateway outcomes remain pending and give access to status instead of retrying a charge',async()=>{const f=checkoutFixture({gatewayError:Error('Fixture timeout')});const response=await f.route.POST(req(body));assert.equal(response.status,503);assert.equal((await response.json()).returnUrl,'https://destekol.org/en/donate/success?donation=fixture');assert.equal(f.updates.find(v=>v.tokenState==='UNKNOWN').tokenState,'UNKNOWN');assert.equal(f.grants(),1);const resumed=checkoutFixture({existing:true,tokenState:'UNKNOWN'});assert.equal((await resumed.route.POST(req(body))).status,409);assert.equal(resumed.calls(),0);});
test('callback rejects forgery and mismatch, acknowledges duplicates and fails closed on save errors',async()=>{for(const [hashValid,amount,saveError,expected]of [[false,3000,false,400],[true,2999,false,400],[true,3000,true,503],[true,3000,false,200]]){let persisted=0;const route=load('app/api/payments/paytr/callback/route.ts',{'@/lib/paytr-settings':{getPayTRSettings:async()=>settings,payTRCredentials:()=>creds},'@/lib/paytr-protocol':protocol,'@/lib/supabase':{getSupabase:()=>({from:()=>({select(){return this},eq(){return this},maybeSingle:async()=>({data:{donationId:'fixture',testMode:false,method:'CARD',donation:{amount:30,currency:'usd'}}})}),rpc:async()=>{persisted++;return{data:false,error:saveError?{}:null}}})}});const oid='DOFixture',total=String(amount),hash=hashValid?createHmac('sha256',creds.merchantKey).update(oid+creds.merchantSalt+'success'+total).digest('base64'):'bad';const request=new NextRequest('http://localhost/callback',{method:'POST',body:new URLSearchParams({merchant_oid:oid,status:'success',total_amount:total,payment_amount:total,hash,currency:'USD',test_mode:'0'})});const response=await route.POST(request);assert.equal(response.status,expected);if(expected===200)assert.equal(await response.text(),'OK');if(expected===400)assert.equal(persisted,0);}});
test('adapter uses exact basket signature and refuses uncertain refund outcomes',async()=>{const adapter=load('lib/paytr-adapter.ts',{'./paytr-protocol':protocol});const original=global.fetch;try{global.fetch=async(url,opts)=>{assert.equal(url,'https://www.paytr.com/odeme/api/get-token');const fields=opts.body;assert.equal(fields.get('payment_amount'),'3000');assert.equal(fields.get('user_address'),'Fixture address');assert.equal(fields.get('merchant_ok_url'),fields.get('merchant_fail_url'));const hash=creds.merchantId+'203.0.113.1'+'DOFixture'+'fixture@destekol.test'+'3000'+fields.get('user_basket')+'1'+'0'+'USD'+'0'+creds.merchantSalt;assert.equal(fields.get('paytr_token'),createHmac('sha256',creds.merchantKey).update(hash).digest('base64'));return{ok:true,json:async()=>({status:'success',token:'a'.repeat(32)})}};await adapter.requestPaymentToken('CARD',{id:'DOFixture',ip:'203.0.113.1',email:'fixture@destekol.test',amount:30,currency:'USD',title:'Fixture'},creds,{name:'Fixture',phone:'123456789',address:'Fixture address'},'https://destekol.org/en/donate/success','en',[['One','10.00',1],['Two','20.00',1]]);global.fetch=async()=>({ok:true,json:async()=>({status:'success',merchant_oid:'DOFixture',return_amount:'5.00',reference_no:'wrong'})});await assert.rejects(()=>adapter.requestRefund('DOFixture',5,'RFfixture',creds));}finally{global.fetch=original;}});
test('refund reserves funds before provider call and preserves pending uncertainty',async()=>{let sent=0,events=[];const route=load('app/api/admin/donations/[id]/refund/route.ts',{'@/lib/admin-access':{requirePermission:async()=>({id:'staff'}),auditAccess:async()=>{},accessErrorResponse:()=>new Response('',{status:503})},'@/lib/supabase':{getSupabase:()=>({from:()=>({select(){return this},eq(){return this},maybeSingle:async()=>({data:{oid:'DOFixture',testMode:false}})}),rpc:async(name)=>{events.push(name);return{error:null}}})},'@/lib/paytr-settings':{getPayTRSettings:async()=>settings,payTRCredentials:()=>creds},'@/lib/payment-lifecycle':lifecycle,'@/lib/paytr-adapter':{GatewayRejected:class extends Error{},requestRefund:async()=>{sent++;assert.equal(events[0],'reserve_paytr_refund');throw Error('Fixture timeout')}}});const response=await route.POST(req({amount:5,reason:'Fixture',requestKey:body.requestKey}),{params:{id:'fixture'}});assert.equal(response.status,202);assert.equal((await response.json()).status,'PENDING');assert.equal(sent,1);assert.deepEqual(events,['reserve_paytr_refund']);});
test('payment secrets use authenticated encryption and never cross public configuration',async()=>{process.env.SUPABASE_JWT_SECRET='unit-test-only-session-secret-at-least-32-bytes';const mod=load('lib/paytr-settings.ts',{'./session-secret':{getSessionSecret:()=>new TextEncoder().encode(process.env.SUPABASE_JWT_SECRET)},'./supabase':{}});const secret='fixture-merchant-secret';const value=mod.encryptPaymentSecret(secret);assert(!value.includes(secret));assert.equal(mod.decryptPaymentSecret(value),secret);assert.throws(()=>mod.decryptPaymentSecret(value.slice(0,-4)+'AAAA'));const publicData=mod.publicPaymentConfig({mode:'LIVE',merchantId:'123',merchantKeyEncrypted:value,merchantSaltEncrypted:value,cardEnabled:true,currencies:['USD']});assert(!JSON.stringify(publicData).includes('merchant'));assert.equal(publicData.monthly,false);});

test('refund permission denial never touches payment settings or provider',async()=>{const route=load('app/api/admin/donations/[id]/refund/route.ts',{'@/lib/admin-access':{requirePermission:async()=>{throw Error('Forbidden')},accessErrorResponse:()=>new Response('',{status:403})},'@/lib/supabase':{getSupabase:()=>assert.fail('No database on denied request')},'@/lib/paytr-settings':{getPayTRSettings:()=>assert.fail('No settings on denied request')},'@/lib/payment-lifecycle':lifecycle,'@/lib/paytr-adapter':{requestRefund:()=>assert.fail('No refund on denied request')}});assert.equal((await route.POST(req({amount:5,reason:'Fixture',requestKey:body.requestKey}),{params:{id:'fixture'}})).status,403);});

test('reports isolate currencies and count cart allocations in their campaigns',async()=>{
 const now=new Date().toISOString(),rows=[{currency:'usd',isTest:false,amount:30,refundedAmount:5,frequency:'ONE_TIME',provider:'PAYTR',createdAt:now,campaignId:null,allocations:[{campaignId:'c1',amount:10,refundedAmount:2,campaign:{title:'One',slug:'one'}},{campaignId:'c2',amount:20,refundedAmount:3,campaign:{title:'Two',slug:'two'}}]},{currency:'try',isTest:false,amount:200,refundedAmount:0,frequency:'ONE_TIME',provider:'PAYTR',createdAt:now,campaignId:null,allocations:[]}];
 for(const [currency,expected]of [['USD',25],['TRY',200]]){
 const db={from:()=>({filters:{},select(){return this},eq(k,v){this.filters[k]=v;return this},gte(){return this},lt(){return this},order(){return this},limit(){return this},then(resolve){return Promise.resolve(resolve({data:rows.filter(row=>row.currency===this.filters.currency&&row.isTest===this.filters.isTest),error:null}));}})};
 const route=load('app/api/admin/reports/route.ts',{'@/lib/admin-access':{requirePermission:async()=>({}),accessErrorResponse:()=>new Response('',{status:403})},'@/lib/supabase':{getSupabase:()=>db}});
 const response=await route.GET(new NextRequest('http://localhost/api/admin/reports?period=7&currency='+currency));const result=await response.json();assert.equal(result.currency,currency);assert.equal(result.totalRaised,expected);assert.equal(result.totalPrev,expected);assert.equal(result.byGateway.PAYTR,expected);assert.equal(result.chart.reduce((n,i)=>n+i.amount,0),expected);if(currency==='USD')assert.equal(result.topCampaigns.reduce((n,c)=>n+c.amount,0),25);
 }
});
test('currency formatting keeps separate net amounts and never sums unlike units',()=>{const money=load('lib/currency-totals.ts');const totals=money.currencyTotals([{currency:'USD',amount:10,refundedAmount:2},{currency:'TRY',amount:200,refundedAmount:50}]);assert.deepEqual(totals,{USD:8,TRY:150});const text=money.formatDonationTotals(totals);assert(text.includes('8.00'));assert(text.includes('150.00'));assert(!text.includes('158.00'));});
