import {NextRequest,NextResponse} from 'next/server';
import {requirePermission,accessErrorResponse,auditAccess} from '@/lib/admin-access';
import {getPayTRSettings,encryptPaymentSecret,PAYMENT_CURRENCIES} from '@/lib/paytr-settings';
import {getSupabase} from '@/lib/supabase';
function safe(s:any){return {mode:s.mode,merchantId:s.merchantId,configured:!!(s.merchantKeyEncrypted&&s.merchantSaltEncrypted),cardEnabled:s.cardEnabled,bankEnabled:s.bankEnabled,currencies:s.currencies};}
export async function GET(req:Request){try{const session=await requirePermission('settings.view',req);if(session.role!=='ADMIN'||session.isStaff){await auditAccess(session,'payments.settings','DENY');return NextResponse.json({error:'Owner only'},{status:403});}return NextResponse.json(safe(await getPayTRSettings()),{headers:{'Cache-Control':'no-store'}});}catch(e){return accessErrorResponse(e);}}
export async function PATCH(req:NextRequest){try{const session=await requirePermission('settings.edit',req);if(session.isStaff)return NextResponse.json({error:'Owner only'},{status:403});const b=await req.json(),old=await getPayTRSettings();
 if(!['DISABLED','TEST','LIVE'].includes(b.mode)||typeof b.merchantId!=='string'||(b.merchantId&&!/^\d{1,20}$/.test(b.merchantId))||typeof b.cardEnabled!=='boolean'||typeof b.bankEnabled!=='boolean'||!Array.isArray(b.currencies)||!b.currencies.length||b.currencies.some((v:unknown)=>typeof v!=='string'||!PAYMENT_CURRENCIES.includes(v)))return NextResponse.json({error:'Invalid settings'},{status:400});
 if(b.bankEnabled&&!b.currencies.includes('TRY'))return NextResponse.json({error:'Bank transfers require TRY to be enabled.'},{status:400});
 if(b.mode==='LIVE'&&old.mode!=='LIVE'&&b.liveActivationConfirmed!==true)return NextResponse.json({error:'Confirm merchant approval and successful test payment first.'},{status:400});
 if(b.merchantId!==old.merchantId||b.merchantKey||b.merchantSalt){const db=getSupabase();const {data:pendingOrders,error:orderError}=await db.from('PayTROrder').select('donationId').is('callbackStatus',null).in('tokenState',['REQUESTING','READY','UNKNOWN']).limit(1);const {data:pendingRefunds,error:refundError}=await db.from('DonationRefund').select('id').eq('provider','PAYTR').eq('status','PENDING').limit(1);if(orderError||refundError)throw new Error('Pending transaction check unavailable');if(pendingOrders?.length||pendingRefunds?.length)return NextResponse.json({error:'Resolve outstanding payments or refunds before changing merchant credentials.'},{status:409});}
 const data:any={mode:b.mode,merchantId:b.merchantId,cardEnabled:b.cardEnabled,bankEnabled:b.bankEnabled,currencies:[...new Set(b.currencies)],updatedAt:new Date().toISOString()};
 for(const [input,column]of [['merchantKey','merchantKeyEncrypted'],['merchantSalt','merchantSaltEncrypted']]){if(b[input]){if(typeof b[input]!=='string'||b[input].length>200||b[input].length<8)return NextResponse.json({error:'Invalid credentials'},{status:400});data[column]=encryptPaymentSecret(b[input]);}}
 if(b.mode!=='DISABLED'&&(!data.merchantId||!(data.merchantKeyEncrypted||old.merchantKeyEncrypted)||!(data.merchantSaltEncrypted||old.merchantSaltEncrypted)))return NextResponse.json({error:'Credentials required'},{status:400});
 await auditAccess(session,'payments.settings.update','ALLOW');const {error}=await getSupabase().from('PayTRSettings').update(data).eq('id','default');if(error)throw error;await auditAccess(session,'payments.settings.update','SUCCESS');return NextResponse.json({ok:true},{headers:{'Cache-Control':'no-store'}});
 }catch(e){return accessErrorResponse(e);}}
