"use client";
import {useEffect,useState,useRef} from 'react';
import Script from 'next/script';
import MonthlyDonationDisclosure from './MonthlyDonationDisclosure';
import { getMonthlyDonationCopy, monthlyAmountLabel } from '@/lib/monthly-donation-copy';
export type CheckoutItem={campaignId:string|null;amount:number;frequency:string};
export default function PaymentCheckout({locale,name,email,items,currency='USD',message='',anonymous=false,onStarted}:{locale:string;name:string;email:string;items:CheckoutItem[];currency?:string;message?:string;anonymous?:boolean;onStarted?:()=>void}){
 const t=(ar:string,en:string,fr:string,tr:string)=>locale==='ar'?ar:locale==='en'?en:locale==='fr'?fr:tr;
 const [config,setConfig]=useState<any>(null),[method,setMethod]=useState<'CARD'|'BANK_TRANSFER'>('CARD'),[phone,setPhone]=useState(''),[address,setAddress]=useState(''),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[payment,setPayment]=useState<any>(null);
 const request=useRef<{key:string;body:string}|null>(null);
 useEffect(()=>{fetch('/api/payments/config',{cache:'no-store'}).then(r=>r.json()).then(setConfig).catch(()=>setConfig({enabled:false}));},[]);
 const [open,setOpen]=useState(true);
 const monthly=items.some(i=>i.frequency.toUpperCase()==='MONTHLY'),mixed=items.some(i=>i.frequency.toUpperCase()!==items[0]?.frequency.toUpperCase());
 const monthlyTotal=items.filter(i=>i.frequency.toUpperCase()==='MONTHLY').reduce((sum,i)=>sum+i.amount,0);
 const available=!monthly&&!mixed&&config?.enabled&&config.currencies.includes(currency)&&(method==='CARD'?config.card:config.bank&&currency==='TRY');
 async function submit(e:React.FormEvent){e.preventDefault();if(!available||!accepted||busy)return;if(name.trim().length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())){setError(t('يرجى إدخال الاسم والبريد الإلكتروني بشكل صحيح.','Please enter a valid name and email address.','Veuillez saisir un nom et une adresse e-mail valides.','Lütfen geçerli bir ad ve e-posta adresi girin.'));return;}setBusy(true);setError('');
 const body={locale,name,email,items:items.map(i=>({...i,frequency:i.frequency.toUpperCase()})),currency,method,phone,address,message,anonymous,policiesAccepted:accepted};
 const serialized=JSON.stringify(body);if(!request.current||request.current.body!==serialized){
 const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(serialized));const hash=Array.from(new Uint8Array(bytes)).map(b=>b.toString(16).padStart(2,'0')).join('');let key=crypto.randomUUID();try{const previous=JSON.parse(sessionStorage.getItem('destekol_payment_request')||'null');if(previous?.hash===hash&&typeof previous.key==='string')key=previous.key;sessionStorage.setItem('destekol_payment_request',JSON.stringify({hash,key}));}catch{}request.current={key,body:serialized};
 }
 try{const res=await fetch('/api/payments/paytr/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,requestKey:request.current.key})});const data=await res.json();if(data.returnUrl){onStarted?.();try{const cache=JSON.parse(sessionStorage.getItem('destekol_payment_request')||'null');if(cache?.key===request.current?.key){cache.donationId=data.donationId||new URL(data.returnUrl,location.origin).searchParams.get('donation');sessionStorage.setItem('destekol_payment_request',JSON.stringify(cache));}}catch{}}if(!res.ok||!data.ok){if(data.returnUrl)setPayment({returnUrl:data.returnUrl,uncertain:true});throw new Error();}setPayment(data);}catch{setError(t('تعذر بدء الدفع. إذا كانت العملية قيد التحقق، تابع حالتها قبل المحاولة مجددًا.','Unable to start payment. If verification is pending, check its status before trying again.','Impossible de démarrer le paiement. Si la vérification est en cours, consultez son statut avant de réessayer.','Ödeme başlatılamadı. Doğrulama bekleniyorsa yeniden denemeden önce işlem durumunu kontrol edin.'));}finally{setBusy(false);}}
 const field='w-full border border-line rounded-xl px-4 py-3 bg-white text-ink text-sm';
 if(payment)return <div className="space-y-4"><p className="text-sm font-bold text-ink">{new Intl.NumberFormat(locale,{style:'currency',currency:payment.currency||currency}).format(payment.amount||items.reduce((sum,i)=>sum+i.amount,0))}</p>{payment.testMode&&<p className="text-sm text-amber-700">{t('وضع الاختبار — هذه العملية ليست تبرعًا فعليًا.','Test mode — this is not a real donation.','Mode test — cette opération n’est pas un don réel.','Test modu — bu işlem gerçek bir bağış değildir.')}</p>}{payment.iframeUrl&&<><Script src="https://www.paytr.com/js/iframeResizer.min.js" onLoad={()=>{(window as any).iFrameResize?.({checkOrigin:['https://www.paytr.com']},'#donation-payment-frame');}}/><iframe id="donation-payment-frame" title={t('الدفع الآمن','Secure payment','Paiement sécurisé','Güvenli ödeme')} src={payment.iframeUrl} className="w-full min-h-[650px] border-0" referrerPolicy="no-referrer" allow="payment"/></>}<a href={payment.returnUrl} className="block text-center rounded-xl bg-brand px-5 py-3 font-bold text-white">{t('متابعة حالة التبرع','Check donation status','Consulter le statut du don','Bağış durumunu kontrol et')}</a>{error&&<p role="alert" className="text-sm text-danger">{error}</p>}</div>;
 if(!open)return <button type="button" aria-expanded={false} onClick={()=>setOpen(true)} className="w-full rounded-xl border border-line p-3 text-sm text-brand">{t('عرض وسائل التبرع','Show donation methods','Afficher les modes de don','Bağış yöntemlerini göster')} ⌄</button>;
 return <form onSubmit={submit} className="space-y-4">
 <div className="flex justify-end"><button type="button" aria-expanded={true} onClick={()=>setOpen(false)} className="text-xs text-brand underline">{t('إخفاء وسائل التبرع','Hide donation methods','Masquer les modes de don','Bağış yöntemlerini gizle')} ⌃</button></div>
 {monthly&&<MonthlyDonationDisclosure amount={monthlyTotal} currency={currency} locale={locale}/>}
 <div className="grid gap-2">{(['CARD','BANK_TRANSFER'] as const).map(value=><button key={value} type="button" aria-pressed={method===value} disabled={monthly||!config?.enabled||(value==='CARD'?!config.card:!config.bank||currency!=='TRY')} onClick={()=>setMethod(value)} className={'rounded-xl border p-3 text-sm font-bold disabled:opacity-45 '+(method===value?'border-brand bg-brand/5 text-brand':'border-line text-muted')}>{value==='CARD'?t('بطاقة بنكية — Visa / Mastercard / TROY','Credit / debit card — Visa / Mastercard / TROY','Carte bancaire — Visa / Mastercard / TROY','Banka / Kredi Kartı — Visa / Mastercard / TROY'):t('تحويل بنكي — Havale / EFT / FAST','Bank transfer — Havale / EFT / FAST','Virement bancaire — Havale / EFT / FAST','Havale / EFT / FAST')}</button>)}</div>
 {available&&method==='CARD'&&<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-muted">{t('رقم الهاتف','Phone number','Téléphone','Telefon')}<input required type="tel" autoComplete="tel" maxLength={20} value={phone} onChange={e=>setPhone(e.target.value)} className={field}/></label><label className="text-sm text-muted">{t('العنوان','Address','Adresse','Adres')}<input required autoComplete="street-address" maxLength={400} value={address} onChange={e=>setAddress(e.target.value)} className={field}/></label></div>}
 <p className="flex flex-wrap gap-x-3 gap-y-1 text-xs text-muted">{[['terms',t('شروط الاستخدام','Terms of use','Conditions d’utilisation','Kullanım koşulları')],['refund-policy',t('الإلغاء والاسترداد','Cancellation and refunds','Annulation et remboursement','İptal ve iade')],['financial-transparency',t('استخدام التبرعات','Use of donations','Utilisation des dons','Bağışların kullanımı')],['privacy',t('الخصوصية','Privacy','Confidentialité','Gizlilik')],['kvkk','KVKK']].map(([slug,label])=><a key={slug} className="underline" target="_blank" rel="noreferrer" href={'/'+locale+'/'+slug}>{label}</a>)}</p>
 {available&&<label className="flex items-start gap-2 text-xs leading-6 text-muted"><input type="checkbox" required checked={accepted} onChange={e=>setAccepted(e.target.checked)} className="mt-1 h-4 w-4 accent-brand"/>{t('اطلعت على شروط التبرع وسياسة الإلغاء والاسترداد.','I have read the donation terms and cancellation and refund policy.','J’ai lu les conditions du don et la politique d’annulation et de remboursement.','Bağış koşullarını ve iptal ve iade politikasını okudum.')}</label>}
 <button disabled={!available||busy} className="w-full rounded-xl bg-accent px-5 py-3.5 text-white font-bold disabled:opacity-50">{busy?'…':monthly?`${getMonthlyDonationCopy(locale).action} — ${monthlyAmountLabel(monthlyTotal,currency,locale)}`:t('متابعة التبرع','Continue donation','Poursuivre le don','Bağışa devam et')}</button>
 {!available&&<p role="status" className="text-xs text-center text-muted">{t('هذه الوسيلة غير متاحة حاليًا للتبرع المحدد.','This method is currently unavailable for the selected donation.','Ce mode de paiement est actuellement indisponible pour le don choisi.','Bu yöntem seçilen bağış için şu anda kullanılamıyor.')}</p>}{config?.testMode&&<p className="text-xs text-amber-700">{t('وضع الاختبار','Test mode','Mode test','Test modu')}</p>}{error&&<p role="alert" className="text-sm text-danger">{error}</p>}
 </form>;
}
