"use client";
import {useEffect,useState} from 'react';
import {adminFetch} from '@/lib/admin-fetch';
export default function PayTRSettingsPanel(){const [data,setData]=useState<any>(null),[key,setKey]=useState(''),[salt,setSalt]=useState(''),[approved,setApproved]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{adminFetch('/api/admin/paytr-settings').then(r=>r.ok?r.json():null).then(setData).catch(()=>{});},[]);
 if(!data)return null;
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await adminFetch('/api/admin/paytr-settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,merchantKey:key,merchantSalt:salt,liveActivationConfirmed:approved})});if(!r.ok){const result=await r.json();throw new Error(result.error||'Save failed');}setKey('');setSalt('');setMessage('Payment settings saved.');}catch(e){setMessage(e instanceof Error?e.message:'Save failed');}finally{setBusy(false);}}
 const field='w-full rounded-xl border border-line px-3 py-2 text-sm';
 return <form onSubmit={save} className="my-6 rounded-2xl border border-line bg-white p-6 space-y-4"><h2 className="font-bold">PayTR payment settings</h2><p className="text-sm text-muted">Only the owner can configure payment activation. Secrets are encrypted and never returned to the browser.</p><div className="grid gap-4 sm:grid-cols-2"><label>Mode<select className={field} value={data.mode} onChange={e=>setData({...data,mode:e.target.value})}><option value="DISABLED">Disabled</option><option value="TEST">Test</option><option value="LIVE">Live</option></select></label><label>Merchant ID<input className={field} value={data.merchantId} onChange={e=>setData({...data,merchantId:e.target.value})}/></label><label>Merchant key<input type="password" autoComplete="new-password" className={field} value={key} onChange={e=>setKey(e.target.value)} placeholder={data.configured?'Saved — leave blank to keep':'Enter key'}/></label><label>Merchant salt<input type="password" autoComplete="new-password" className={field} value={salt} onChange={e=>setSalt(e.target.value)} placeholder={data.configured?'Saved — leave blank to keep':'Enter salt'}/></label></div><label className="flex gap-2"><input type="checkbox" checked={data.cardEnabled} onChange={e=>setData({...data,cardEnabled:e.target.checked})}/>Card payments enabled for this merchant</label><label className="flex gap-2"><input type="checkbox" checked={data.bankEnabled} onChange={e=>setData({...data,bankEnabled:e.target.checked})}/>Bank transfer service approved (TRY only)</label><div className="flex flex-wrap gap-4">{['USD','TRY','EUR','GBP','RUB'].map(currency=><label key={currency} className="flex gap-2"><input type="checkbox" checked={data.currencies.includes(currency)} onChange={e=>setData({...data,currencies:e.target.checked?[...data.currencies,currency]:data.currencies.filter((c:string)=>c!==currency)})}/>{currency}</label>)}</div><p className="text-xs text-muted">Recurring donations remain unavailable until card storage and Non3D recurring permissions and enrollment are implemented for the approved service.</p>{data.mode==='LIVE'&&<label className="flex gap-2 text-sm"><input required type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>Merchant approved, currencies authorized, callback configured, and a successful test payment verified.</label>}<p className="text-xs text-muted break-all">Notification URL: https://destekol.org/api/payments/paytr/callback</p><button disabled={busy} className="rounded-xl bg-brand px-5 py-3 font-bold text-white disabled:opacity-50">{busy?'Saving…':'Save payment settings'}</button>{message&&<p role="status" className="text-sm">{message}</p>}</form>;
}
